import os
import json
import smtplib
import random
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# =========================
# 邮件配置（GitHub Secrets）
# =========================
SMTP_SERVER = os.getenv("SMTP_SERVER")
SMTP_PORT = int(os.getenv("SMTP_PORT", "465"))
EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
RECEIVER_EMAIL = os.getenv("RECEIVER_EMAIL")

# =========================
# 读取航线数据
# =========================
with open("routes.json", "r", encoding="utf-8") as f:
    routes = json.load(f)["routes"]

# =========================
# 模拟价格（后续可接真实API）
# =========================
def get_price(route):
    base = random.randint(1200, 9000)
    return base

# =========================
# 生成报告数据
# =========================
results = []

for r in routes:
    price = get_price(r)

    results.append({
        "route": f"广州 → {r['city']}",
        "price": price,
        "airline": "模拟航司",
        "transit": "1次中转",
        "baggage": "行李直挂",
        "visa": "通常无需过境签"
    })

# =========================
# 生成HTML邮件内容
# =========================
today = datetime.now().strftime("%Y-%m-%d")

html = f"""
<html>
<head>
    <style>
        body {{ font-family: Arial; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; }}
        th {{ background-color: #f2f2f2; }}
    </style>
</head>
<body>

<h2>Weekly Flight Price Report</h2>
<p>Date: {today}</p>

<table>
<tr>
<th>航线</th>
<th>价格</th>
<th>航司</th>
<th>中转</th>
<th>行李</th>
<th>签证</th>
</tr>
"""

for r in results:
    html += f"""
<tr>
    <td>{r['route']}</td>
    <td>¥{r['price']}</td>
    <td>{r['airline']}</td>
    <td>{r['transit']}</td>
    <td>{r['baggage']}</td>
    <td>{r['visa']}</td>
</tr>
"""

html += """
</table>

<p style="margin-top:20px;">Auto generated by GitHub Actions</p>

</body>
</html>
"""

# =========================
# 发送邮件
# =========================
msg = MIMEMultipart()
msg["Subject"] = "Weekly Flight Monitor Report"
msg["From"] = EMAIL_USER
msg["To"] = RECEIVER_EMAIL

msg.attach(MIMEText(html, "html"))

try:
    server = smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT)
    server.login(EMAIL_USER, EMAIL_PASSWORD)
    server.sendmail(EMAIL_USER, RECEIVER_EMAIL, msg.as_string())
    server.quit()

    print("邮件发送成功")
except Exception as e:
    print("邮件发送失败:", e)
