import os
import json
import requests
import smtplib
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ======================
# 环境变量
# ======================
SMTP_SERVER = os.getenv("SMTP_SERVER")
SMTP_PORT = int(os.getenv("SMTP_PORT") or 465)
EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
RECEIVER_EMAIL = os.getenv("RECEIVER_EMAIL")

# ======================
# 读取航线
# ======================
with open("routes.json", "r", encoding="utf-8") as f:
    routes = json.load(f)["routes"]

# ======================
# ✈️ v2：模拟真实API（后面可替换）
# ======================
def get_flight_data(route):
    """
    未来这里可以替换成：
    - Amadeus API
    - Skyscanner API
    - Kiwi API
    """

    # 模拟多航班返回
    flights = []

    for i in range(3):
        flights.append({
            "route": f"广州 → {route['city']}",
            "price": 2000 + i * 800,
            "airline": ["南航", "国泰", "新航"][i],
            "stops": i,  # 0=直飞
            "transit_time": 2 + i * 5,  # 小时
            "baggage": True,
            "visa_risk": "low" if i < 2 else "medium"
        })

    return flights

# ======================
# ✈️ v2过滤规则
# ======================
def filter_flights(flights):
    result = []

    for f in flights:
        # 条件1：中转时间不超过12小时
        if f["transit_time"] > 12:
            continue

        # 条件2：优先直飞
        score = 100 - f["price"] / 100

        if f["stops"] == 0:
            score += 30

        # 条件3：行李优先
        if f["baggage"]:
            score += 10

        # 条件4：签证风险
        if f["visa_risk"] == "low":
            score += 10

        f["score"] = round(score, 2)
        result.append(f)

    return sorted(result, key=lambda x: x["score"], reverse=True)

# ======================
# 数据收集
# ======================
all_results = []

for r in routes:
    flights = get_flight_data(r)
    best = filter_flights(flights)[0]
    all_results.append(best)

# ======================
# HTML报告
# ======================
today = datetime.now().strftime("%Y-%m-%d")

html = f"""
<html>
<body>
<h2>✈️ Weekly Flight Monitor v2</h2>
<p>Date: {today}</p>

<table border="1" cellpadding="8">
<tr>
<th>航线</th>
<th>价格</th>
<th>航空公司</th>
<th>中转次数</th>
<th>中转时间</th>
<th>评分</th>
</tr>
"""

for f in all_results:
    html += f"""
<tr>
<td>{f['route']}</td>
<td>¥{f['price']}</td>
<td>{f['airline']}</td>
<td>{f['stops']}</td>
<td>{f['transit_time']}h</td>
<td>{f['score']}</td>
</tr>
"""

html += """
</table>
<p>Auto generated by Flight Monitor v2</p>
</body>
</html>
"""

# ======================
# 发邮件
# ======================
msg = MIMEMultipart()
msg["Subject"] = "✈️ Weekly Flight Monitor v2"
msg["From"] = EMAIL_USER
msg["To"] = RECEIVER_EMAIL

msg.attach(MIMEText(html, "html"))

try:
    server = smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT)
    server.login(EMAIL_USER, EMAIL_PASSWORD)
    server.sendmail(EMAIL_USER, RECEIVER_EMAIL, msg.as_string())
    server.quit()
    print("邮件发送成功")
except Exception as e:
    print("邮件发送失败:", e)
